#install.packages("reticulate")
# bslib::bs_theme_preview()

#detach("package:reticulate", unload = TRUE)
library(shiny)
library(bslib)
library(thematic)
library(reticulate)
library(TheOpenAIR)
library(glue)
library(DT)
library(pdftools)
#library(jinjar)
use_python("/Users/lilian.do-khac/.pyenv/versions/3.11.4/bin/python")
py_install("aleph-alpha-client")
py_install("Jinja2")

