proxy:
  title: Generative AI Showcase Meadow
  logo-url: 
  landing-page: /
  heartbeat-rate: 10000
  container-wait-time: 60000
  heartbeat-timeout: 60000
  port: 8080
  authentication: simple
  admin-groups: admin
  users:
    - name: admin
      password: admin
      groups: admin
    - name: user
      password: password
      groups: user
  docker:
    internal-networking: true
  specs:
    - id: llm-playground
      display-name: Aleph Alpha Playground Dupe and Showcases
      description: R SHINY Front-end for LLMs to abstract from the account level and showcasing use cases with LLMs. 
      container-image: schiggy89/llm-playground
      access-groups: [ admin, user ]
      container-network: shinyproxy
   # - id: 00
   #   display-name: Admin Console
   #   container-image: 
   #   access-groups: admin

logging:
  level: 
    root: INFO
  file:
    name: shinyproxy.log