version: "3"
services:
  aa_playground:
    image: aa_playground
    # volumes:
    #  - ${INPUT_DIRECTORY}:/input
    #  - ${OUTPUT_DIRECTORY}:/output
    environment:
      PASSWORD: mypassword
    ports:
      - 8787:8787